"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/global/nav-bar";
import Footer from "@/components/global/footer";
import { usePathname } from "next/navigation";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAdminRoute = pathname.includes("/admin");
  const isArtistRoute = pathname.includes("/artist");

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sebez Visual Art</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={inter.className}>
        {!isAdminRoute && !isArtistRoute && <NavBar />}
        <main>{children}</main>
        {!isAdminRoute && !isArtistRoute && <Footer />}
        <Toaster />
      </body>
    </html>
  );
}
